### ISSUE TITLE
你好，请问这个如何可以使用java实现？

### ISSUE THREAD

**Issue by aigeek** [zhoutk/wikiSpider#1]
你好，看了你的文章，请问这个如何可以使用java实现？

**Comment by zhoutk** [comment]
哪个语言都可以实现，我用node.js实现主要是想用cheerio这样的DOM分析库，在java中，你就要去找合适的库，或者自己用正则表达式去处理。另：node.js天然的异步编程，就不需要象java一样去做多线程编程了，呵呵！
